services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./mysql/
    expose:
      - 3306
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - mysql-db:/var/lib/mysql
    env_file:
      - ./mysql/local.env
    tty: true
  api:
    depends_on:
      - mysql
    container_name: api
    platform: linux/x86_64
    build: ./api
    restart: unless-stopped
    tty: true
    expose:
      - 8000
    links:
      - "mysql:mysql"
    volumes:
      - ./api:/app
    env_file:
      - ./api/local.env
  frontend:
    container_name: frontend
    depends_on:
      - api
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
volumes:
  mysql-db: